README.md, package.json
This allows the user to choose their version.
=> Make prettier a peerDependency

README.md
Hey!
I noticed while following the readme, that the install order is wrong.
Installing `eslint-plugin-prettier` before `prettier` yield this error:
```
├── eslint-plugin-prettier@2.0.1
└── UNMET PEER DEPENDENCY prettier@>= 0.11.0
npm WARN eslint-plugin-prettier@2.0.1 requires a peer of prettier@>= 0.11.0 but none was installed.
```
So I swapped the steps in the readme. Cheers!
=> Change the order of dependencies install

README.md
Updating the example section to use the correct option, there's no `true` anymore,
The available options are: `none`, `es5` and `all`,
Also, adding a link to the API section, https://github.com/prettier/prettier#api, where you can find more options and the correct values
=> README - Updating prettier options in example

CONTRIBUTING.md, README.md
The travis sticker is currently broken:
=> Docs: update repo links to new URL

CHANGELOG.md
It looks like I need to improve my release script, right now it assumes that the result of `git config --get remote.origin.url` is an `https:` URL.
=> Docs: fix links in changelog

.travis.yml, eslint-plugin-prettier.js
Converting from a range/index to a location varies between ESLint versions. This PR covers versions all the way back to ESLint 3.9.0, and creates a test matrix of the various versions.
Context: Unfortunately, we have a project with ESLint 3.9.0 that I can't update right now without making a mess.
=> Fix: Support ESLint <3.11.0

CONTRIBUTING.md, build/release.js, package.json, yarn.lock
The mentioned in https://github.com/prettier/eslint-plugin-prettier/pull/21#issuecomment-301575481 (https://github.com/not-an-aardvark/eslint-config/blob/c4518a7a/build/release.js). It's been tweaked to conform to Prettier style.
=> Chore: Add release script

.eslintrc.js, eslint-plugin-prettier.js, package.json, test/prettier.js
=> feat: expose reporter api

.eslintrc.js, package.json, yarn.lock
This updates the ESLint config to use [`eslint-plugin-self`](https://github.com/not-an-aardvark/eslint-plugin-self) rather than monkeypatching ESLint's internals.
=> Chore: use eslint-plugin-self for linting

README.md
Figured it was worth specifying the .json extension because it takes higher precedence: https://eslint.org/docs/user-guide/configuring#configuration-file-formats
.eslintrc.json is what is recommended in prettier's README: https://github.com/prettier/prettier#eslint
.eslintrc is also slightly ambiguous given it can contain YAML
=> .eslintrc.json > .eslintrc

README.md, eslint-plugin-prettier.js, test/prettier.js, test/prettierrc/bracket-spacing/.prettierrc, test/prettierrc/double-quote/.prettierrc, test/prettierrc/single-quote/.prettierrc, yarn.lock
I'm not sure if anybody was working on this issue so I made this PR !
Tests are passing, and I tested it on a small example project.
Cheers
=> Fix: Support prettier v1.6.0 config (#46)

eslint-plugin-prettier.js
We are on prettier 1.5.2 in a project, so it explodes with new version of the plugin.
```
Error while loading rule 'prettier/prettier': prettier.clearConfigCache is not a function
TypeError: Error while loading rule 'prettier/prettier': prettier.clearConfigCache is not a function
at Object.create (/Users/simbekkh/repos/process-exception-handlers/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:341:20)
at Object.keys.forEach.ruleId (/Users/simbekkh/repos/process-exception-handlers/node_modules/eslint/lib/linter.js:957:44)
at Array.forEach (<anonymous>)
at Linter._verifyWithoutProcessors (/Users/simbekkh/repos/process-exception-handlers/node_modules/eslint/lib/linter.js:897:35)
at preprocess.map.textBlock (/Users/simbekkh/repos/process-exception-handlers/node_modules/eslint/lib/ …
```
=> Guard against older prettier installation

README.md, eslint-plugin-prettier.js
=> New: Add 'recommended' configuration

eslint-plugin-prettier.js
ESLint v4.15.0 added an official location for rules to store a URL to their documentation in the rule metadata in eslint/eslint#9788. This adds the URL to all the existing rules so anything consuming them can
know where their documentation is without having to resort to external packages to guess.
=> Add URL to rule documentation to the metadata

eslint-plugin-prettier.js, package.json, yarn.lock
Passing the filepath to Prettier allows Prettier to determine which parser to use dynamically. This has the effect of fixing the integration between `eslint-plugin-vue` or `eslint-plugin-html` and `eslint-plugin-prettier`, but is not specific to those plugins.
Here's a test showing the output after this fix: https://github.com/azz/eslint-vue-prettier-repro
I added a test to this repo but could not commit it as it depends on a HTML parser being loaded.
=> Fix: pass filepath to prettier

README.md, eslint-plugin-prettier.js, test/prettier.js
Hello! This PR adds an option to allow you to skip loading the prettierrc file. I have a use case for this in some external tooling and it would really come in handy.
=> Add option to skip loading prettierrc

README.md
=> Add clarification notice about Flow/React support to the readme

.prettierignore, .travis.yml, .vscode/settings.json, LICENSE.md, README.md, package.json, yarn.lock
Chore: Add format script to run prettier
Run the format script and commit updates
---
Chore: Improve travis matrix
Ensure we test with eslint 3.x, 4.x and 5.x, and node 10
Fixes #97
---
Chore: Add vscode config to autoformat on save
=> Prettier formatting and Travis updates

eslint-plugin-prettier.js, package.json, test/invalid/vue-syntax-error.txt, test/prettier.js, yarn.lock
If Prettier can't format a file due to not being able to parse the given
content it throws a SyntaxError. If that happens then announce the
error as an ESLint rule violation instead of crashing.
The most plausible form of SyntaxErrors are when vue files contain invalid HTML such as no self-closing tags (e.g. `<template><div></template>` is invalid due to there being no `</div>`
Fixes #140.
=> Catch and format SyntaxErrors as eslint violations

README.md, eslint-plugin-prettier.js, test/invalid/18.txt, test/prettier.js
https://github.com/prettier/eslint-plugin-prettier/pull/118 seems to be abandoned. Trying to revive it by implementing the changes asked for in the code review.
=> New: Allow options to be passed to prettier.getFileInfo

.travis.yml, package.json, yarn.lock
Skipping the node 6 build on current as eslint 6 dropped support for it as it is EOL. We still support eslint 5 so it's not worth removing it from our support yet.
=> Add eslint 6 to test matrix

eslint-plugin-prettier.js
This avoids a deprecation notice
With thanks to @robertoentringer for spotting this
=> When forcing the JS parser, use the modern name

eslint-plugin-prettier.js
This lets custom file types specified in prettierrc be found if you're
using prettier v1.19
=> Resolve config when getting list of inferred parsers

eslint-plugin-prettier.js
Per https://eslint.org/docs/user-guide/command-line-interface#fix-type , one can set `meta` to "problem" or "suggestion" for code-related changes or "layout" for formatting ones. Setting this value allows `eslint --fix-type` to take into account the type of fix desired. (And I'm making an eslint badge formatter for which it is more convenient to have this meta info so any rule violations can be grouped by type.)
=> Set `meta.type` to "layout"

.travis.yml, package.json, yarn.lock
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉
devDependencies should be compatible with ESLint 7 too before we can merge this one:
---
BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x
Closes #292
=> Add tests for running ESLint 7

eslint-plugin-prettier.js
At Airbnb we've noticed that the Prettier ESLint rule is extraordinarily
slow. When running ESLint with `TIMING=1`, Prettier is two orders of
magnitude slower than our other slowest rules (which come from
eslint-plugin-import mostly).
I spent some time investigating this today. I ran the Chrome DevTools
profiler while running ESLint on a directory with 480 files in it.
Looking at the flame charts, I noticed that this plugin ended up calling
Prettier's pluginSearchDirs.map.pluginSearchDir for every file that was
being linted, even though it was being memoized. Through some logging, I
determined that the Prettier cache was being cleared between every file,
and narrowed it down to this line, which was added here:
https://github.com/prettier/eslint-plugin-prettier/pull/55#discussion_r139307523 …
=> Avoid clearing Prettier cache when not using prettierrc

README.md, eslint-plugin-prettier.js
https://github.com/prettier/eslint-config-prettier/pull/168 is moving `arrow-body-style` and `prefer-arrow-callback` (which conflict with eslint-plugin-prettier, #65) from the `prettier` config to its own file, `prettier/prettier`. The reason for doing this is:
- We don’t want to turn off those rules for all Prettier users who _don’t_ use eslint-plugin-prettier.
- Since those exclusions are specific to eslint-plugin-prettier, it makes sense to put them in a separate file just like we do for all other plugins.
This PR turns off those two rules in the `recommended` config. This helps people upgrade:
- People can upgrade eslint-plugin-prettier but not eslint-config-prettier without any problems.
- People who upgrade both can keep using the `recommended` config without issues.
This PR also …
=> Turn off problematic rules in recommended config (prepare for next eslint-config-prettier version)

.github/workflows/ci.yml
The version of chalk that gets installef with eslint 6 requires node 10.
=> Skip CI for eslint 6 + node 8

eslint-plugin-prettier.js
Fixes #304
This halfs the time taken on CLI runs. However when you make a config
change your editor won't pick up that change until you reload your
editor window (either by restarting your editor, or in VSCode there is a
"Reload window" command).
Given that most of the time you're not adjusting your config, this
speedup is worth that extra bit of friction.
**After this change your editor's eslint plugin will not instantly pick up config changes in `.prettierrc`.** I suggest moving your prettier config into package.json - which eslint plugins should already be watching as it may effect eslint configuration changes. Worst case scenario you'll need to restart your editor after changing your prettier configuration.
On my [test repo](https://github.com/shopify/polaris-react), getting timing …
=> Minor: Do not clear the config cache on each run

package.json
**What's the problem this PR addresses?**
https://github.com/prettier/eslint-plugin-prettier/pull/367 added a peer dependency on `eslint-plugin-prettier` instead of `eslint-config-prettier`
**How did you fix it?**
Changed the peer dependency from `eslint-plugin-prettier` to `eslint-config-prettier`
=> fix: add eslint-config-prettier as an optional peer dependency

README.md
Once https://github.com/prettier/eslint-config-prettier/pull/175 is merged, these instructions are obsolete.
(Edit: The linked PR is merged now, and v8.0.0 has been released. This is ready to be merged.)
=> Remove instructions on separate eslint-config-prettier configs

eslint-plugin-prettier.js, test/prettier.js
=> feat: support processor virtual filename

.github/workflows/ci.yml
Current CI is broken because of `@graphql-eslint/eslint-plugin` 2.0
cc @BPScott
=> ci: @graphql-eslint/eslint-plugin has dropped node 10

.editorconfig, .eslintrc.js, .github/workflows/ci.yml, .prettierrc, eslint-plugin-prettier.js, package.json, test/invalid/10.txt, test/invalid/11-a.txt, test/invalid/11-b.txt, test/invalid/graphql.txt, test/prettier.js, test/prettierrc/no-semi/.prettierrc, yarn.lock
This PR contains breaking changes that shall go into v4 of eslint-plugin-prettier. API and usage remains the same, however we drop support for old and unsupported versions of eslint, prettier and node. This allows us to use recent features like eslint's `context.getPhysicalFilename()` instead of writing workarounds.
- eslint v7.28.0 is the minimum supported version of eslint
- prettier v2.0.0 is the minimum supported version of prettier
- node v12 is the minimum supported version of node (we don't enforce this with an engines field, and this should work on node 10 but we're not going to test this on CI so use the now-EOL node 10 at your own risk)
=> v4 - Drop support for eslint 5/6, prettier 1, node 6/8

.github/workflows/ci.yml, package.json, yarn.lock
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
devDependency compatibility with ESLint 8:
---
I wanted to update `eslint-config-prettier`, `eslint-plugin-eslint-plugin`, `eslint-plugin-node` & `vue-eslint-parser` to their latest minor, but that would break CI on the older ESLint/Node versions
If wanted, I can do it in this PR or make a second PR with all the breaking changes.
**Edit**: This can be done without a breaking change after #429 is merged
---
Closes #427
=> chore(CI): add tests for ESLint 8

.changeset/odd-eagles-breathe.md, eslint-plugin-prettier.js, package.json, test/fixtures/@ota-meshi/eslint-plugin-svelte/App.svelte, test/fixtures/eslint-plugin-svelte3/App.named-blocks.svelte, test/fixtures/eslint-plugin-svelte3/App.svelte, test/prettier.js, yarn.lock
close #472, close #482
We recommend to use [`eslint-plugin-svelte`](https://github.com/ota-meshi/eslint-plugin-svelte) instead of `eslint-plugin-svelte3`.
=> feat: support svelte out of box

README.md
For the fundings, I suggest you open a joined account on opencollective, but before that I guess we can use @JounQin's personal account.
But I don't think display all those unrelated orgs in README is the right thing.
=> Remove `Sponsors` and `Backers` section from README.md

.changeset/stale-guests-battle.md, worker.js
Fixes https://github.com/prettier/eslint-plugin-prettier/issues/563
In `prettier@3.0.0` the behavior of plugins list default value was changed
from this:
https://github.com/prettier/prettier/blob/e154250e19caa6d1b23bb1e7803ee5f8d0f95445/src/common/load-plugins.js#L25-L27
to this:
https://github.com/prettier/prettier/blob/266344398c1c90f7dc7b206ba8077cecc294470f/src/main/plugins/load-plugins.js#L3
So `plugins: null` causes runtime error, the default value should be `undefined` as declared [there](https://github.com/prettier/prettier/blob/266344398c1c90f7dc7b206ba8077cecc294470f/src/index.d.ts#L784)
=> fix: compatibility with prettier@3 without plugins

.changeset/thick-birds-share.md, worker.js
Fix this issue #584
to compatibility with Eslint Flat Config.
`parserPath` might be `undefined` and will throw error on worker. so check parserPath is string type before usage.
Maybe we can remove whole `svelte` block since [`eslint-plugin-svelte3`](https://github.com/sveltejs/eslint-plugin-svelte3) is deprecated
=> fix: `parserPath` type might be `undefined` on Eslint Flat Config

eslint-plugin-prettier.js
But keep supporting the methods for now.
I think this might be considered a `chore` as it won't affect users of the plugin until ESLint v10 is released.
=> chore: use context properties where context methods are deprecated

package.json, pnpm-lock.yaml
In preparation for https://github.com/prettier/eslint-plugin-prettier/pull/592. To make it possible to only include what's explicitly related to flat config format in that PR.
=> chore: bump @types/eslint

.changeset/five-tools-matter.md, eslint-plugin-prettier.js
Extracted from #592.
Adding a meta block improves debugability and caching in the flat config system. See https://eslint.org/docs/latest/extend/plugins#meta-data-in-plugins
=> feat: add meta block to config

.changeset/old-doors-kiss.md, README.md, eslint.config.js, package.json, recommended.d.ts, recommended.js
Fixes #591.
Fixes #592.
Original ideas extracted from #592.
Add flat recommended config file. Unlike the legacy recommended file this only enables the prettier rule and disables `arrow-body-style` and `arrow-body-style`. It does not enable anything from `eslint-config-prettier`. 
It is now the responsibility of the consumer to enable both `eslint-plugin-prettier` and `eslint-config-prettier`. Configs extending other configs is complicated and not transparent. We should trust the user to configure their configs directly. In a future major change we should remove `eslint-config-prettier` from the legacy config too, as over lap between the responsibilities of `eslint-plugin-prettier` and `eslint-config-prettier` have always been a bit confusing and "a plugin goes and enables configs from …
=> Add flat recommended config

.changeset/slimy-boats-fold.md, package.json
Fix #622.
Add exports mapping to package.json, to allow `import eslintPluginRecommended from 'eslint-plugin-prettier/recommended'` to work as expected.
Strictly speaking this is a breaking change as it removes the ability for people to import from "eslint-plugin-prettier/eslint-plugin-prettier.js" and "eslint-plugin-prettier/recommended.js" but the former was never a good idea in the first place and the latter has only been available for a few days, so I'm not worried about closing off those two import paths in a non-major release.
=> fix: add package.json exports field

.changeset/slimy-boats-fold.md, .changeset/warm-cougars-attack.md, .prettierrc, eslint-plugin-prettier.js, eslint.config.js, package.json, patches/@types__eslint@8.44.7.patch, pnpm-lock.yaml, test/fixtures/md.md, test/prettier.js, worker.js
The following is unnecessary anymore when using with `eslint-mdx`/`eslint-plugin-mdx`!
```json5
[
{
files: ["**/*.md"],
rules: { "prettier/prettier": ["error", { parser: "markdown" }] },
},
{
files: ["**/*.mdx"],
rules: { "prettier/prettier": ["error", { parser: "mdx" }] },
},
]
```
=> feat: support parsing `markdown` via `eslint-mdx` natively

.changeset/rich-pigs-allow.md, package.json
It's very common to read the `package.json`, this is not a required but nice-to-have entry.
=> chore: add `package.json` into `exports` map

README.md
Noticed the legacy config link was broken
Quick PR to fix it
=> docs(README): fixes legacy ESlint configs link

.changeset/giant-bottles-sin.md, eslint-plugin-prettier.js, test/fixtures/invalid-prettierrc/.prettierrc.cjs, test/fixtures/invalid-prettierrc/test.js, test/prettier.js
=> fix: report node when loc not found

.changeset/healthy-seas-add.md, recommended.js
=> chore: add plugin name to flat recommended config

test/prettier.mjs
`loadESLint()` will look for config file.
Use `eslintUnsupportedApi.FlatESLint ?? eslintPackage.ESLint` should be a better way.
=> test: improve how to get `FlatESLint`
